📰🌉 Updated with Glitch

diff --git a/pokemon-showdown b/pokemon-showdown
--- a/pokemon-showdown
+++ b/pokemon-showdown
@@ -1,32 +1,56 @@
-#!/usr/bin/env node
+#!/bin/sh
 
-// Before running, ensure that the Typescript files have been compiled.
-//
-// Simply doing `require('../build')` here doesn't work because the `replace`
-// step of the build is asynchronous and we can't wait for it to finish easily
-// unless we shell out and use `execSync`. However, the heuristic of simply
-// checking for the presence of  './.sim-dist/dex' to determine whether a build
-// is required is somewhat risky as it only is valid from a clean repository -
-// if you make edits or have previous build artifacts lying arround, this
-// script could potentially be missing additional sources or the compiled output
-// may be out of date.
-//
-// We're OK with risking being stale here unless we're starting the server
-// because we want to keep this script as fast as possible to be usable as a way
-// of interfacing with the simulator from non-JS languages. Otherwise we error
-// on the side of caution and run `node build` to ensure we're always running
-// with the latest code.
-var built = false;
-function build() {
-	require('child_process').execSync('node build', {stdio: 'inherit', cwd: __dirname});
-	built = true;
-}
+true /*
+# Shell script will interpret above as a command and execute everything after
+# it, while JavaScript will interpret this as beginning of a comment and skip
+# shell script contents.
+#
+# As shell script parses lines only when they are needed, nothing after exit 1
+# can possibly cause a syntax error.
+
+if nodepath="$(command -v node || command -v nodejs)"; then
+	exec "$nodepath" "--trace-warnings" "$0" "$@"
+fi
+echo "We require Node.js version 8 or later; Node.js not found"
+exit 1
+*/;
+
+var child_process = require('child_process');
+var fs = require('fs');
+var path = require('path');
+
+// # Make sure we're Node 8+
 
 try {
-	require.resolve('./.sim-dist/dex');
+	eval('{ let a = async () => {}; }');
+} catch (e) {
+	console.log("We require Node.js version 8 or later; you're using " + process.version);
+	process.exit(1);
+}
+
+// # Make sure our dependencies are available, and install them if they
+// # aren't
+
+try {
+	require.resolve('sockjs');
+} catch (e) {
+	console.log('Installing dependencies...');
+	child_process.execSync('npm install --production', {stdio: 'inherit'});
+}
+
+// # Make sure config.js exists. If not, copy it over synchronously from
+// # config-example.js, since it's needed before we can start the server
+
+try {
+	require.resolve('./config/config');
 } catch (err) {
 	if (err.code !== 'MODULE_NOT_FOUND') throw err; // should never happen
-	build();
+
+	console.log('config.js does not exist. Creating one with default settings...');
+	fs.writeFileSync(
+		path.resolve(__dirname, 'config/config.js'),
+		fs.readFileSync(path.resolve(__dirname, 'config/config-example.js'))
+	);
 }
 
 if (!process.argv[2] || /^[0-9]+$/.test(process.argv[2])) {
@@ -37,7 +61,6 @@ if (!process.argv[2] || /^[0-9]+$/.test(process.argv[2])) {
 	// host on port 9000:
 	// $ ./pokemon-showdown 9000
 
-	if (!built) build();
 	require('module')._load('./server', module, true);
 } else switch (process.argv[2]) {
 	case 'help':
@@ -66,7 +89,7 @@ if (!process.argv[2] || /^[0-9]+$/.test(process.argv[2])) {
 		console.log('pokemon-showdown simulate-battle');
 		console.log('');
 		console.log('  Simulates a battle, taking input to stdin and writing output to stdout');
-		console.log('  Protocol is documented in ./.sim-dist/README.md');
+		console.log('  Protocol is documented in ./sim/README.md');
 		console.log('');
 		console.log('pokemon-showdown unpack-team');
 		console.log('');
@@ -86,24 +109,23 @@ if (!process.argv[2] || /^[0-9]+$/.test(process.argv[2])) {
 	case 'start':
 		{
 			process.argv[2] = process.argv[3];
-			if (!built) build();
 			require('module')._load('./server', module, true);
 			break;
 		}
 	case 'generate-team':
 		{
-			var Dex = require('./.sim-dist/dex').Dex;
-			global.toID = Dex.getId;
+			var Dex = require('./sim/dex');
+			global.toId = Dex.getId;
 			var seed = process.argv[4] ? process.argv[4].split(',').map(Number) : undefined;
-			console.log(Dex.packTeam(Dex.generateTeam(process.argv[3], {seed})));
+			console.log(Dex.packTeam(Dex.generateTeam(process.argv[3], seed)));
 		}
 		break;
 	case 'validate-team':
 		{
-			var Dex = require('./.sim-dist/dex').Dex;
-			var TeamValidator = require('./.sim-dist/team-validator');
+			var Dex = require('./sim/dex');
+			var TeamValidator = require('./sim/team-validator');
 			var validator = TeamValidator(process.argv[3]);
-			var Streams = require('./.lib-dist/streams');
+			var Streams = require('./lib/streams');
 			var stdin = new Streams.ReadStream(process.stdin);
 
 			stdin.readLine().then(function (textTeam) {
@@ -124,23 +146,22 @@ if (!process.argv[2] || /^[0-9]+$/.test(process.argv[2])) {
 		break;
 	case 'simulate-battle':
 		{
-			var BattleTextStream = require('./.sim-dist/battle-stream').BattleTextStream;
-			var Streams = require('./.lib-dist/streams');
+			var BattleTextStream = require('./sim/battle-stream').BattleTextStream;
+			var Streams = require('./lib/streams');
 			var stdin = new Streams.ReadStream(process.stdin);
 			var stdout = new Streams.WriteStream(process.stdout);
 
 			var battleStream = new BattleTextStream({
 				debug: process.argv[3] === '--debug'
 			});
-			battleStream.start();
 			stdin.pipeTo(battleStream);
 			battleStream.pipeTo(stdout);
 		}
 		break;
 	case 'unpack-team':
 		{
-			var Dex = require('./.sim-dist/dex').Dex;
-			var Streams = require('./.lib-dist/streams');
+			var Dex = require('./sim/dex');
+			var Streams = require('./lib/streams');
 			var stdin = new Streams.ReadStream(process.stdin);
 
 			stdin.readLine().then(function (packedTeam) {
@@ -157,8 +178,8 @@ if (!process.argv[2] || /^[0-9]+$/.test(process.argv[2])) {
 		break;
 	case 'pack-team':
 		{
-			var Dex = require('./.sim-dist/dex').Dex;
-			var Streams = require('./.lib-dist/streams');
+			var Dex = require('./sim/dex');
+			var Streams = require('./lib/streams');
 			var stdin = new Streams.ReadStream(process.stdin);
 
 			stdin.readLine().then(function (unpackedTeam) {
